server:
    port: 8182
    context-path:

logging:
    level:
        tk.mybatis: DEBUG
        #查看mybatis语句输出
        com.dhcc.ecm.business.mybatis: DEBUG
        org.springframework.security: DEBUG
security:
    basic:
        enabled: false
spring:
    application:
        name: upload # Service registers under this name
    datasource:
        #url: jdbc:mysql://127.0.0.1:3306/fastpan
        #username: root
        #password: root

        url: jdbc:oracle:thin:@105.erjinzhi.net:1521:orcl
        username: itemmg
        password: password

        type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: oracle.jdbc.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    http:
        multipart:
            max-request-size: 5120MB
            max-file-size: 2048MB
multipart:
    max-file-size: 2048MB
    maxRequestSize: 5120MB
    maxFileSize: 2048Mb
flyway:
  enabled: false